# Generated by Django 5.1.6 on 2025-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                db_index=True,
                help_text="10 или 13-значный номер ISBN",
                max_length=13,
                unique=True,
            ),
        ),
    ]
